### ISSUE TITLE
Mobility1 low arrival rate

### ISSUE THREAD

**Issue by Arceliar** [mwarning/meshnet-lab#10]
I was running the mobility1 test, and saw that I get low arrival rates for everything I test. The arrival rate seems to almost perfectly match what is shown in the results page for bmx7, at least for the routing schemes that were expected to get ~100%.

Using `batman-adv` to test, the problem seems to appear in b2418a778852410b4a5e142844d61cd669e2fbaf. I *think* the problem is that `filter_paths` sets `max_hops` to `math.inf` in cases where the value wasn't set. My guess is the length of a path to an unreachable node is probably also `math.inf`, so that's `<=` the (infinite) max hops, and the path isn't filtered out. There's probably a clean way to fix this in `filter_paths`, but I haven't had a chance to test anything yet.

**Comment by mwarning** [comment]
I have added your changes.
