### ISSUE TITLE
ping_deadline can cause unwanted behavior

### ISSUE THREAD

**Issue by b-reich** [mwarning/meshnet-lab#17]
I think there is a Issue with the `ping_deadline = 1`
In larger networks or in networks with more delay this can result in unwanted packetlost.

https://github.com/mwarning/meshnet-lab/blob/d5f32ce5a4a75f1da52c8d86d0248ac698ce1886/ping.py#L321-L352

I can write a PR for a parameter if you like

**Comment by mwarning** [comment]
hi, yes please. That is an edge case that should be covered.
