### ISSUE TITLE
having problem with installing olsr2 protocol

### ISSUE THREAD

**Issue by Machynko** [mwarning/meshnet-lab#29]
returning an error when installing olsr2 protocol with make install

**Comment by Machynko** [comment]
fixed

**Comment by Machynko** [comment]
May I ask you if you could somehow help me to implement blockchain
technology to this simulation? I would be really thankful to you because I
am struggling a bit with it.


ut 10. 5. 2022 o 16:26 Moritz Warning ***@***.***> napísal(a):

**Comment by mwarning** [comment]
That is not something I can help with.
