### ISSUE TITLE
Use a proper license

### ISSUE THREAD

**Issue by jcgruenhage** [mwarning/meshnet-lab#3]
See https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense/147120#147120 for the problems the Unlicense has. CC0 has a very similar meaning and more reliable legal fallbacks in Jurisdictions where the Unlicense is unclear or explicitly illegal.

**Comment by mwarning** [comment]
I've changed the license to CC0. I despise licenses.

**Comment by jcgruenhage** [comment]
Yeah, I wish we didn't have to deal with them either, but as long as we need to, I'll try to help people avoid mistakes that might cause someone trouble later
