### ISSUE TITLE
topo construction is slow

### ISSUE THREAD

**Issue by liecn** [mwarning/meshnet-lab#31]
Hi,

Thanks for your efforts!

I tested the grid4-1089 topology. It needs 7.5 hrs to set up the network, which is so slow. I wonder if there is any chance we can make it faster?

Thanks!

 

Please find the logs below

```
cleared on 2 remotes in 18.326s
run yggdrasil on ../../data/grid4/grid4-1089.json
Network setup in 7.51h:
  nodes: 1089 created, 0 removed, 0 updated
  links: 2112 created, 0 removed, 0 updated
started yggdrasil in 1089 namespaces in 13.47m
Wait 30s for the nodes start up and discover each other (needed for proactive protocols).
```

**Comment by mwarning** [comment]
That is very long. I see that you use two remotes. In the default configuration, for every  command a new ssh session will be established. That is very very slow. 

You can speed this up ~100x by using [SSH Connection Sharing](https://github.com/mwarning/meshnet-lab#ssh-connection-sharing)

I want to make this even faster in the future and without any need to workarounds.

**Comment by liecn** [comment]
Wow! Let me try this one! Thanks, my friend!

Best,

**Comment by mwarning** [comment]
Did it work?

**Comment by liecn** [comment]
It works but still slow. I’m trying to refactor the command queue.

Thanks.

Best,
Chenning Li
________________________________

**Comment by mwarning** [comment]
Hi, thank you for the feedback. There is still lot of improvement. Feel free to contribute any improvements if you feel the quality is fine.

**Comment by mwarning** [comment]
Network creation has now sped up 2-4x.
